### PR TITLE
53 convenience function to set filepath via command line argument

### PR DESCRIPTION
**Pull request by tjadevries**

### CODE REVIEW

**Comment by tjadevries** [comment]
This PR builds on https://github.com/StockwatchDev/application_settings/pull/52

**Comment by JJdeVries** [comment]
@tjadevries there are 52 commits in this merge, where the commit message are very often similar. Is it an idea to interactively rebase this merge on top of issue 51 and remove some of the extraneous commits? It's an workflow I'm usually pretty happy with, to **rebase** feature branches (usually on top of develop), as they are mostly only for a single developer to work on (and can be pulled rather easily using `git pull --rebase` by other developers), while `develop` (and other shared branches) use merge commits to update to avoid changing history.

**Comment by tjadevries** [comment]
Agreed. It's new for me but I'd like to learn this way. Will do the rebase on top of develop after merge of #51

**Comment by JJdeVries** [comment]
@tjadevries if you need help I can show how I usually do it this saturday/sunday. Although I'm usually only really using the cmdline, not sure if you're using some GUI wrapper.

**Pull request closed without merging**
